### ISSUE TITLE
Broken CI/CD?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Documentation#1]
https://docs.laravel-enso.com/guide/getting-started.html#installation-steps still shows the old installation steps (cleared my cache)

![image](https://user-images.githubusercontent.com/932193/45100022-f0b4f780-b128-11e8-89a0-961012b3dc2d.png)

**Comment by y0net** [comment]
This is what i see on docs.laravel-enso.com:

![image](https://user-images.githubusercontent.com/19207797/45105774-b2760300-b13d-11e8-86e6-b7c5a0df917c.png)

The only difference is at step 4

**Comment by aocneanu** [comment]
I suppose it's something related to our webserver's caching policy. Try clearing your cache or opening the docs in a private browser.

**Comment by jlsjonas** [comment]
@aocneanu looks like a pretty bad policy as I tried a "disabled cache" request too...

![image](https://user-images.githubusercontent.com/932193/45143140-ab410a80-b1ba-11e8-86d0-68ac14b65cdc.png)

I had to open the exact url in private mode & then give it another refresh to load the updated version; quite unexpected & definitely unwanted after more than a week...

**Comment by aocneanu** [comment]
Yeah I know, the site is hosted on netlify and apparently we're doing something wrong...

https://www.netlify.com/blog/2015/09/11/instant-cache-invalidation/

But I truly have bigger problems on my plate now. Maybe you can discover what we're missing ;)

**Comment by jlsjonas** [comment]
@aocneanu Discovered the issue... the service-worker you're using is basically preventing the invalidation; hence why it does immediately updates in incognito mode.

the worker gets updated; but is stuck in a waiting state until **all** tabs are closed. Which can cause SIGNIFICANT delays if some tab is left open somewhere

https://stackoverflow.com/questions/33262385/service-worker-force-update-of-new-assets could be helpful ;)

**Comment by jlsjonas** [comment]
@aocneanu ping :)
I'm having to resort to private mode for an up to date version of the docs again 😁

**Comment by jlsjonas** [comment]
It's still the same issue actually; time doesn't fix it.

I have the updated version on my computer already; but the serviceworker is _stuck_ waiting as refresh doesn't work.

In the case of the docs site the service worker should (as mentioned in my oct 2 message) trigger a skipWaiting, as you expect updates to _go live_ asap, instead of _providing consistency during the session_ (default behaviour)

**Comment by aocneanu** [comment]
https://www.netlify.com/blog/2015/09/11/instant-cache-invalidation/
