### ISSUE TITLE
Edit Field

### ISSUE THREAD

**Issue by novusfederico** [laravel-enso/Documentation#11]
Hello i have a problem to edit field. I have an error, if i set the field to editable the systemshow me an error "type fild is not valid"

How can i resolve this issue?

**Comment by novusfederico** [comment]
I want something like this:
[screenshot](https://user-images.githubusercontent.com/45257537/52438840-7c88e080-2b1a-11e9-8b07-e146d9735cf7.png)

**Comment by aocneanu** [comment]
Is this documentation related?

**Comment by novusfederico** [comment]
in the documentation it is only written that one can use that type of field, but its not documented anywhere
