### ISSUE TITLE
datepicker does not work with a Carbon instance

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Documentation#12]
>dateFormat, string, sets the default date format for datepicker fields. Note that for this fields and instance of Carbon is expected

Under [Form Builder's Global config](https://docs.laravel-enso.com/packages/form-builder.html#global-configuration), when trying to pass a Carbon instance to a datepicker (using `$this->form->value(` in `ModelForm`'s `create()` it results in an `[Object] Object` being displayed, instead of a date.

What's the expected way to pass a _default_ date to it? (taking localisation into account)

**Comment by aocneanu** [comment]
You can follow the example from person form. The birthday is casted as date (carbon).

Note the you may use a format option in the field config that will precede the format provided in `config/enso/forms.php`

**Comment by jlsjonas** [comment]
Person form does not set a date by default though;
I temporarily solved it by doing a `->toDateString()` but this was not aware of the config (which wasn't present in my case, it's addition was missing from `CHANGELOG.md`)
updated to `$myCarbonDate->format(config('enso.forms.dateFormat'))`; though the documentation implies I should've just passed the Carbon instance directly. I'd suggest either updating docs to clarify, or update `form->value` to parse the date according to dateFormat itself (which is probably the better option as the format can be overridden per field, which wouldn't be a DRY operation if changed using the _current_ method)

**Comment by aocneanu** [comment]
Aaah, lol got it now. It's a but in the form package.

**Comment by aocneanu** [comment]
closed with laravel-enso/formbuilder#lastcommit:)

**Comment by jlsjonas** [comment]
Didn't realize it was a bug 😅

**Comment by aocneanu** [comment]
lol, that's a first :P
