### ISSUE TITLE
Manifest.json is missing, prevents service-worker from updating

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/documentation#15]
![image](https://user-images.githubusercontent.com/932193/54680853-3193bd00-4b0b-11e9-91de-287bb6255fc0.png)

~~At first glance this is an oversight in vuepress' upgrade guide, as [the service worker setting](https://vuepress.vuejs.org/config/#serviceworker) now defaults to false.~~
It looks like the `manifest,json` was provided outside of the repo (perhaps by netlify?)

Either way, it's currently not there anymore meaning that anyone who ever visited the docs site will keep getting the old docs served from the local cache (even after a force refresh; on subsequent visits; as the service worker takes over _next time_ again)

(I'd provide a PR if I had more experience with VuePress & the config used, sadly that's not the case)

**Comment by aocneanu** [comment]
access in chrome:

`chrome://serviceworker-internals/`

Then manually unregister the previous service worker.

Let's leave this open.

**Comment by jlsjonas** [comment]
Aware of the workaround, but afaik these don't expire so will cause confusion to anyone who checked the framework out before

**Comment by aocneanu** [comment]
This is why we will keep this open and refer to it if somebody asks. At least until we'll have a better idea.

**Comment by jlsjonas** [comment]
I understand,

From what I see the service worker is still added as a configuration option but just no longer present.
I'm not sure what caused it to be unavailable in later builds.

I did notice you've included the [v1 pwa plugin](https://github.com/laravel-enso/Documentation/blame/master/package.json#L7); but are _still_ using 0.x

That might be causing some conflict leading into this?

**Comment by aocneanu** [comment]
@jlsjonas

**Comment by jlsjonas** [comment]
As mentioned in https://github.com/laravel-enso/enso/pull/214#issuecomment-489551526 (& confirmed just now) the issue still persist & will persist until a proper manifest is provided again under `https://docs.laravel-enso.com/manifest.json`

**Comment by aocneanu** [comment]
finally addressed
