### ISSUE TITLE
Document frontend enum class

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/documentation#18]
Starting point: https://github.com/laravel-enso/Helpers/pull/10#issuecomment-487488818

> You should add local enums to a `LocalStateBuilder` and reuse the `bootEnums` helper available in the FE.
> 
> The you can do
> 
> ```js
> computed: {
>    ...mapState('local', ['enums']),
> }
> 
> ....
> 
> $this.enums.myEnum._get(key)`
> ```
> 
> [usage example](https://github.com/enso-ui/ui/blob/master/src/bulma/pages/administration/users/components/UserProfile.vue#L139)
> 
> [full api](https://github.com/enso-ui/ui/blob/master/src/modules/plugins/Enum.js)

**Comment by jlsjonas** [comment]
@aocneanu can you check/confirm https://github.com/laravel-enso/Helpers/pull/10#issuecomment-487562361 so I can work on this?
Thanks

**Comment by aocneanu** [comment]
@jlsjonas I guess I did :)

**Comment by jlsjonas** [comment]
Will be looking at it next week, been very busy.
