### ISSUE TITLE
Updates - procedure clarification

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/documentation#25]
In regards to :

> When we must make breaking changes to the packages, we increase the minor version. Due to how dependencies are defined, composer will not update the dependencies for you in that case, that's why you need to look at the changelog, be aware of the changes, update your code and then manually update the dependencies' minor version, so that you can continue to receive updates.

https://docs.laravel-enso.com/guide/usage.html#updates

I just want to clarify one thing:
If I run `composer update` it will not update laravel-enso\enso + all other enso dependncies like laravel-enso\table, laravel-enso\select, laravel-enso\data-export etc..?

By 
>update your code
you mean I need to manually merge all changes from current changelog into my local vendor\laravel-enso ...?

Or all enso related changes are merged but only version is not updated?
>manually update the dependencies' minor version

This is confusing for me because on `composer update` I see some things getting updates from laravel-enso, but version remains the local one...

**Comment by aocneanu** [comment]
Composer manages your dependencies (vendor folder) as specified in composer.json.

The local project (what you are cloning) is a different story.

You should really get familiar with how composer / git works before diving into Enso.

**Comment by robbykrlos** [comment]
> Composer manages your dependencies (vendor folder) as specified in composer.json.
> 
> The local project (what you are cloning) is a different story.
> 
> You should really get familiar with how composer / git works before diving into Enso.

Oh, thank you, I had some understanding issues. Sorry for not closing the ticket sooner.
