### ISSUE TITLE
Help understanding user/roles/usergroups concept for documentation and future permission expansion

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/documentation#28]
Hi,

I'm reading this: https://docs.laravel-enso.com/guide/under-the-hood.html#usergroups-roles-users

> - users represent the operators using the application
> - roles are collections of permissions
> - user groups (previously owners) can represent departments, types, and even companies
> - an user group can have many users
> - an user group can have many roles
> - an user has just one user group and just one role
> - the role of a user may only be one of the roles available for its user group
> - users have an active or inactive status, where inactive users cannot login or make requests in the application (but can set/reset their password)
> - the Role model contains the AdminId and SupervisorId constants that determine who the administrator and supervisor roles are
> - the UserGroup model contains the AdminGroupId constant that is used to determine which is the Administrator user group

and I understand each point independently, but all together I'm missing the global purpose and why were those things implemented this way.

What is the purpose of having a user linked to a UserGroup/Role pair, if in the end it's the role sets of permissions that matters. Why have the UserGroup in the first place?

Is is just for pure classification so that you have different, let's say... companies permissions under the same usergroup?

I'm trying to investigate the possibility to expand this functionality to multiple sets of permissions per user. Let's say if a user works for 2 companies, and it has 2 different roles in each company, I wouldn't like to create 2 users for the same person, therefore, I'm thinking to give multiple roles to the same user. This scenario will generate permission conflicts, but a simple rule as "the highest permission wins" will work for me (if one role has "read only" and another has "read/write" - the global merged permission will be "read/write"). And I'm not sure if maybe I can work with what is already implemented, and I'm missing some things, or, I was not intended this way, and I have to implement this solution.

Thank you.

**Comment by aocneanu** [comment]
Search the issues on enso for ‘roles’ and read the related, was discussed before

**Comment by robbykrlos** [comment]
Hi,

Ok found https://github.com/laravel-enso/enso/issues/6. Thank you!

Should I also understand that you will not accept contributions going this way ?
