### ISSUE TITLE
Changing backend logic

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/documentation#29]
In regards to :

https://docs.laravel-enso.com/guide/development.html#changing-back-end-logic

> If the modifications you require are more extensive and cannot be resolved via using dependency injection, the other option is to overwrite the required routes, and point to your local implementation/controllers.

Can you give me an example of using dependency injection ? I'm trying to piece together this scenario where I need to extend your "permissions", let's say, by having another related entity to it, therefore I need your permissions to have a "belongsToMany". 

I'm also considering using tentacles (https://github.com/greabock/tentacles) on all Models...

PS: based on your answer I'll add also to the documentation everything that may be helpful.

**Comment by aocneanu** [comment]
I'm not really sure if that's what you're asking but:

```php

namespace App\Models;

use LaravelEnso\Permissions\app\Models\Permission as BasePermission;

class Permission extends BasePermission
{
       public function localRelation()
       {
              return this->belongsToMany(LocalRelation::class);
       }
}

```

in your local `AppServiceProvider`

```php
    public $bindings = [
          BasePermission::class => PermissionClass
    ];
```

Now in controllers the resolved permission class will be the local one.

If you need to overwrite an action (controller) bind it too.

**Comment by robbykrlos** [comment]
Hi,

Ok, thanks, that helped. I've updated the documentation as well - I did a pull request.

Thank you.
