### ISSUE TITLE
section "getting-started / Installation Steps" missing "vendor:publish -all"

### ISSUE THREAD

**Issue by Cyrille37** [laravel-enso/documentation#36]
Hi,
Section "getting-started / Installation Steps" missing the step for :
`php artisan vendor:publish --all`
Without the web app does not work, isn't it ?
Cheers

**Comment by aocneanu** [comment]
Are you using an enso clone?

**Comment by Cyrille37** [comment]
Yep: `git clone git@github.com:laravel-enso/enso.git`

**Comment by Cyrille37** [comment]
Sorry for noise, I've done an install again, and not need of `artisan vendor:publish --all`.
